### ISSUE TITLE
📝 Study about the difference between Pointer and Reference

### ISSUE THREAD

**Issue by gabrieldejesus** [gabrieldejesus/42-cpp-module-01#4]
### 📋 Tasks

- [ ] Difference Between Pointer and Reference
- [ ] What is a Pointer?
- [ ] What is a Reference?
- [ ] Similarities Between Pointer and Reference

## 📝 Notes
